config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :statuses
  resources :priorities
  resources :verticals
  resources :request_types
  resources :roles
  resources :tasks
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get "password_resets/edit"

  root "sessions#new"

  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"

  resources :users do
    member do
      get "/serve_small",  action: "serve_small"
      get "/serve_medium", action: "serve_medium"
      get "/serve_large",  action: "serve_large"
    end
  end

  get ":id/serve_doc", to: "attachments#serve_doc"
  get ":id/serve_thumb", to: "attachments#serve_thumb"

  get "/delete_avatar", to: "users#destroy_avatar" # TODO: Fix this
  get "/delete_doc", to: "attachments#destroy" # TODO: Fix this
end

app/models/vertical.rb
class Vertical < ApplicationRecord
  has_many :tasks, dependent: :restrict_with_error
  validates :name, presence: true
end

app/controllers/verticals_controller.rb
class VerticalsController < ApplicationController
  include ReadableErrors
  load_and_authorize_resource
  before_action :set_vertical, only: [:show, :edit, :update, :destroy]

  # GET /verticals
  # GET /verticals.json
  def index
    @verticals = Vertical.all
  end

  # GET /verticals/1
  # GET /verticals/1.json
  def show
  end

  # GET /verticals/new
  def new
    @vertical = Vertical.new
  end

  # GET /verticals/1/edit
  def edit
  end

  # POST /verticals
  # POST /verticals.json
  def create
    @vertical = Vertical.new(vertical_params)
    respond_to do |format|
      if @vertical.save
        format.html { redirect_to @vertical, notice: t("vertical.created") }
        format.json { render :show, status: :created, location: @vertical }
      else
        format.html { render :new }
        format.json { render json: @vertical.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /verticals/1
  # PATCH/PUT /verticals/1.json
  def update
    respond_to do |format|
      if @vertical.update(vertical_params)
        format.html { redirect_to @vertical, notice: t("vertical.updated") }
        format.json { render :show, status: :ok, location: @vertical }
      else
        format.html { render :edit }
        format.json { render json: @vertical.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /verticals/1
  # DELETE /verticals/1.json
  def destroy
    respond_to do |format|
      if @vertical.destroy
        format.html { redirect_to verticals_url, notice: t("vertical.destroyed") }
        format.json { head :no_content }
      else
        format.html { redirect_to(verticals_url, alert: formated_errors(@vertical)) }
        format.json { render json: @vertical.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_vertical
    @vertical = Vertical.find(params[:id])
  end

  def vertical_params
    params.require(:vertical).permit(:name, :description)
  end
end

app/views/verticals/_form.html.erb
<div class="form_div">
  <%= form_for(vertical) do |f| %>
    <% if vertical.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(vertical.errors.count, "error") %> <%= t("errors.plural")%></h2>

        <ul>
        <% vertical.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, class:"simple_input" %>
    </div>

    <div class="field">
      <%= f.label :description %>
      <%= f.text_field :description, class:"simple_input" %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/verticals/edit.html.erb
<h1 class="object_title">Editing Vertical</h1>

<%= render "form", vertical: @vertical %>

<div class="bottom_link">
  <%= link_to "Show", @vertical %> |
  <%= link_to "Back", verticals_path %>
</div>

app/views/verticals/index.html.erb
<h1 class="object_title">Verticals</h1>

<table class="table table-responsive table-hover table-bordered sub_data">
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
    <% @verticals.each do |vertical| %>
      <tr>
        <td><%= vertical.name %></td>
        <td><%= vertical.description %></td>
        <td><%= link_to "Show", vertical %></td>
        <td><%= link_to "Edit", edit_vertical_path(vertical) %></td>
        <td><%= link_to "Destroy", vertical, method: :delete, data: { confirm: t(:confirm) } %></td>
      </tr>
    <% end %>
</table>

<div class="bottom_link">
  <%= link_to "New Vertical", new_vertical_path %>
</div>

app/views/verticals/new.html.erb
<h1 class="object_title">New Vertical</h1>

<%= render "form", vertical: @vertical %>

<div class="bottom_link">
  <%= link_to "Back", verticals_path %>
</div>

app/views/verticals/show.html.erb
<div class="show_div">
  <p>
    <strong>Name:</strong>
    <%= @vertical.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @vertical.description %>
  </p>

  <%= link_to "Edit", edit_vertical_path(@vertical) %> |
  <%= link_to "Back", verticals_path %>
</div>