config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :statuses
  resources :priorities
  resources :verticals
  resources :request_types
  resources :roles
  resources :tasks
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get "password_resets/edit"

  root "sessions#new"

  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"

  resources :users do
    member do
      get "/serve_small",  action: "serve_small"
      get "/serve_medium", action: "serve_medium"
      get "/serve_large",  action: "serve_large"
    end
  end

  get ":id/serve_doc", to: "attachments#serve_doc"
  get ":id/serve_thumb", to: "attachments#serve_thumb"

  get "/delete_avatar", to: "users#destroy_avatar" # TODO: Fix this
  get "/delete_doc", to: "attachments#destroy" # TODO: Fix this
end

app/models/priority.rb
class Priority < ApplicationRecord
  has_many :tasks, dependent: :restrict_with_error
  validates :name, presence: true
end

app/controllers/priorities_controller.rb
class PrioritiesController < ApplicationController
  include ReadableErrors
  load_and_authorize_resource
  before_action :set_priority, only: [:show, :edit, :update, :destroy]

  # GET /priorities
  # GET /priorities.json
  def index
    @priorities = Priority.all
  end

  # GET /priorities/1
  # GET /priorities/1.json
  def show
  end

  # GET /priorities/new
  def new
    @priority = Priority.new
  end

  # GET /priorities/1/edit
  def edit
  end

  # POST /priorities
  # POST /priorities.json
  def create
    @priority = Priority.new(priority_params)
    respond_to do |format|
      if @priority.save
        format.html { redirect_to @priority, notice: t("priority.created") }
        format.json { render :show, status: :created, location: @priority }
      else
        format.html { render :new }
        format.json { render json: @priority.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /priorities/1
  # PATCH/PUT /priorities/1.json
  def update
    respond_to do |format|
      if @priority.update(priority_params)
        format.html { redirect_to @priority, notice: t("priority.updated") }
        format.json { render :show, status: :ok, location: @priority }
      else
        format.html { render :edit, notice: formated_errors(@priority) }
        format.json { render json: @priority.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /priorities/1
  # DELETE /priorities/1.json
  def destroy
    respond_to do |format|
      if @priority.destroy
        format.html { redirect_to priorities_url, notice: t("priority.destroyed") }
        format.json { head :no_content }
      else
        format.html { redirect_to(priorities_url, alert: formated_errors(@priority)) }
        format.json { render json: @priority.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_priority
    @priority = Priority.find(params[:id])
  end

  def priority_params
    params.require(:priority).permit(:name, :description)
  end
end

app/views/priorities/_form.html.erb
<div class="form_div">
  <%= form_for(priority) do |f| %>
    <% if priority.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(priority.errors.count, "error") %> <%= t("errors.plural")%></h2>
        <ul>
          <% priority.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, class:"simple_input" %>
    </div>

    <div class="field">
      <%= f.label :description %>
      <%= f.text_field :description, class:"simple_input" %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/priorities/edit.html.erb
<h1 class="object_title">Editing Priority</h1>

<%= render "form", priority: @priority %>

<div class="bottom_link">
  <%= link_to "Show", @priority %> |
  <%= link_to "Back", priorities_path %>
</div>

app/views/priorities/index.html.erb
<h1 class="object_title">Priorities</h1>

<table class="table table-responsive table-hover table-bordered sub_data">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th colspan="3"></th>
  </tr>
  <% @priorities.each do |priority| %>
    <tr>
      <td><%= priority.name %></td>
      <td><%= priority.description %></td>
      <td><%= link_to "Show", priority %></td>
      <td><%= link_to "Edit", edit_priority_path(priority) %></td>
      <td><%= link_to "Destroy", priority, method: :delete, data: { confirm: t(:confirm) } %></td>
    </tr>
  <% end %>
</table>

<div class="bottom_link">
  <%= link_to "New Priority", new_priority_path %>
</div>

app/views/priorities/new.html.erb
<h1 class="object_title">New Priority</h1>

<%= render "form", priority: @priority %>

<div class="bottom_link">
  <%= link_to "Back", priorities_path %>
</div>

app/views/priorities/show.html.erb
<div class="show_div">
  <p>
    <strong>Name:</strong>
    <%= @priority.name %>
  </p>
  <p>
    <strong>Description:</strong>
    <%= @priority.description %>
  </p>
  <%= link_to "Edit", edit_priority_path(@priority) %> |
  <%= link_to "Back", priorities_path %>
</div>