config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :statuses
  resources :priorities
  resources :verticals
  resources :request_types
  resources :roles
  resources :tasks
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get "password_resets/edit"

  root "sessions#new"

  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"

  resources :users do
    member do
      get "/serve_small",  action: "serve_small"
      get "/serve_medium", action: "serve_medium"
      get "/serve_large",  action: "serve_large"
    end
  end

  get ":id/serve_doc", to: "attachments#serve_doc"
  get ":id/serve_thumb", to: "attachments#serve_thumb"

  get "/delete_avatar", to: "users#destroy_avatar" # TODO: Fix this
  get "/delete_doc", to: "attachments#destroy" # TODO: Fix this
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Help Desk</title>
    <%= favicon_link_tag "rook.ico" %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
            <% if logged_in? %>
              <li><a href="/tasks"><%= t("layout.tasks") %></a></li>
              <li><%= link_to t("layout.create_new_task"), new_task_path %></li>
            <% if can? :manage, User %>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= t("layout.users") %>
                <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to t("layout.users_index"), users_path %></li>
                  <li><%= link_to t("layout.new_user"), new_user_path %></li>
                </ul>
              </li>
            <% end %>
            <% if current_user.role.name == Role::ADMIN %>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= t("layout.data") %>
                <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="/verticals"><%= t("layout.verticals") %></a></li>
                  <li><a href="/request_types"><%= t("layout.request_types") %></a></li>
                  <li><a href="/priorities"><%= t("layout.priorities") %></a></li>
                  <li><a href="/statuses"><%= t("layout.statuses") %></a></li>
                  <li><a href="/roles"><%= t("layout.roles") %></a></li>
                </ul>
              </li>
              <% end %>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li><%= link_to( t("layout.edit_account"), edit_user_path(current_user) ) %></li>
              <li><%= link_to "Logout", logout_path %> </li>
            <% else %>
              <li><%= link_to( t("layout.login"), new_session_path, method: :delete) %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container-fluid text-center">
      <div class="row content">
        <div class="col-sm-12 text-left">
          <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
    <div class="footer">
    </div>
  </body>
</html>